const Data = [

        {
            "playerId": 1636758291593,
            "playerName": "Eoin Morgan",
            "playerTeam": "kkr",
            "themeEndColor": "#301857",
            "themeStartColor": "#6F45AC",
            "playerImage": "https://i.ibb.co/fCHqSL5/Eoin-Morgan-ce08ed0c.png",
            "playerRole": "batsman",
            "isCaptain": true,
            "nationality": "English",
            "totalMatches": 17,
            "totalRuns": 133,
            "totalWickets": 0,
            "dateOfBirth": "10 September 1986",
            "iplDebut": 2010
        },
        {
            "playerId": 1636758300998,
            "playerName": "Sunil Narine",
            "playerTeam": "kkr",
            "themeEndColor": "#301857",
            "themeStartColor": "#6F45AC",
            "playerImage": "https://i.ibb.co/Km0mGC6/Sunil-Narine-23633ab1.png",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 14,
            "totalRuns": 62,
            "totalWickets": 16,
            "dateOfBirth": "26 May 1988",
            "iplDebut": 2012
        },
        {
            "playerId": 1636758481826,
            "playerName": "Shivam Mavi",
            "playerTeam": "kkr",
            "themeEndColor": "#301857",
            "themeStartColor": "#6F45AC",
            "playerImage": "https://i.ibb.co/QKxykxP/Shivam-Mavi-9c3cf3a5.png",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 9,
            "totalRuns": 25,
            "totalWickets": 11,
            "dateOfBirth": "26 November 1998",
            "iplDebut": 2018
        },
        {
            "playerId": 1636758731017,
            "playerName": "Andre Russell",
            "playerTeam": "kkr",
            "themeEndColor": "#301857",
            "themeStartColor": "#6F45AC",
            "playerImage": "https://i.ibb.co/yyT50j9/Andre-Russell-2068dce5.png",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 10,
            "totalRuns": 183,
            "totalWickets": 11,
            "dateOfBirth": "29 April 1988",
            "iplDebut": 2012
        },
        {
            "playerId": 1636758742859,
            "playerName": "Dinesh Karthik",
            "playerTeam": "kkr",
            "themeEndColor": "#301857",
            "themeStartColor": "#6F45AC",
            "playerImage": "https://i.ibb.co/xCB75cF/Dinesh-Karthik-fde9080f.png",
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 17,
            "totalRuns": 223,
            "totalWickets": 0,
            "dateOfBirth": "01 June 1985",
            "iplDebut": 2008
        },
        {
            "playerId": 1636815441704,
            "playerName": "Mayank Agarwal",
            "playerTeam": "kxp",
            "themeEndColor": "#F64749",
            "themeStartColor": "#B31619",
            "playerImage": "https://i.ibb.co/BP9hCyz/158.webp",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 12,
            "totalRuns": 441,
            "totalWickets": 0,
            "dateOfBirth": "18 February 1991",
            "iplDebut": 2011
        },
        {
            "playerId": 1636815824419,
            "playerName": "Nicholas Pooran",
            "playerTeam": "kxp",
            "themeEndColor": "#F64749",
            "themeStartColor": "#B31619",
            "playerImage": "https://i.ibb.co/BsJ0BG5/1703.webp",
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 12,
            "totalRuns": 85,
            "totalWickets": 0,
            "dateOfBirth": "02 October 1995",
            "iplDebut": 2019
        },
        {
            "playerId": 1636816230746,
            "playerName": "Arshdeep Singh",
            "playerTeam": "kxp",
            "themeEndColor": "#F64749",
            "themeStartColor": "#B31619",
            "playerImage": "https://i.ibb.co/4VnHJjJ/4698.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 12,
            "totalRuns": 2,
            "totalWickets": 18,
            "dateOfBirth": "05 February 1999",
            "iplDebut": 2019
        },
        {
            "playerId": 1636816758690,
            "playerName": "Mohammad Shami",
            "playerTeam": "kxp",
            "themeEndColor": "#F64749",
            "themeStartColor": "#B31619",
            "playerImage": "https://i.ibb.co/gTYMCS3/94.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 14,
            "totalRuns": 13,
            "totalWickets": 19,
            "dateOfBirth": "03 September 1990",
            "iplDebut": 2009
        },
        {
            "playerId": 1636817231184,
            "playerName": "Kane Williamson",
            "playerTeam": "srh",
            "themeEndColor": "#F37107",
            "themeStartColor": "#EFBC44",
            "playerImage": "https://i.ibb.co/2Y4Ng58/440.webp",
            "playerRole": "batsman",
            "isCaptain": true,
            "nationality": "New Zealander",
            "totalMatches": 10,
            "totalRuns": 266,
            "totalWickets": 0,
            "dateOfBirth": "08 August 1990",
            "iplDebut": 2015
        },
        {
            "playerId": 1636817716887,
            "playerName": "Jonny Bairstow",
            "playerTeam": "srh",
            "themeEndColor": "#F37107",
            "themeStartColor": "#EFBC44",
            "playerImage": "https://i.ibb.co/v346XTP/506.webp",
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "English",
            "totalMatches": 7,
            "totalRuns": 248,
            "totalWickets": 0,
            "dateOfBirth": "26 September 1989",
            "iplDebut": 2019
        },
        {
            "playerId": 1636817955360,
            "playerName": "Bhuvneshwar Kumar",
            "playerTeam": "srh",
            "themeEndColor": "#F37107",
            "themeStartColor": "#EFBC44",
            "playerImage": "https://i.ibb.co/MkTj8cX/116.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 11,
            "totalRuns": 34,
            "totalWickets": 6,
            "dateOfBirth": "05 February 1990",
            "iplDebut": 2011
        },
        {
            "playerId": 1636818119542,
            "playerName": "Jason Holder",
            "playerTeam": "srh",
            "themeEndColor": "#F37107",
            "themeStartColor": "#EFBC44",
            "playerImage": "https://i.ibb.co/18tGsLP/1075.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 8,
            "totalRuns": 85,
            "totalWickets": 16,
            "dateOfBirth": "05 November 1991",
            "iplDebut": 2013
        },
        {
            "playerId": 1636818284102,
            "playerName": "Rashid Khan",
            "playerTeam": "srh",
            "themeEndColor": "#F37107",
            "themeStartColor": "#EFBC44",
            "playerImage": "https://i.ibb.co/5jRvJPM/2885.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Afghan",
            "totalMatches": 14,
            "totalRuns": 83,
            "totalWickets": 18,
            "dateOfBirth": "20 September 1998",
            "iplDebut": 2017
        },
        {
            "playerId": 1636819627869,
            "playerName": "Rohit Sharma",
            "playerTeam": "mi",
            "themeEndColor": "#0764AB",
            "themeStartColor": "#10D6D5",
            "playerImage": "https://i.ibb.co/ykcDrc9/107.webp",
            "playerRole": "batsman",
            "isCaptain": true,
            "nationality": "Indian",
            "totalMatches": 13,
            "totalRuns": 381,
            "totalWickets": 0,
            "dateOfBirth": "30 April 1987",
            "iplDebut": 2008
        },
        {
            "playerId": 1636819813209,
            "playerName": "Quinton de Kock",
            "playerTeam": "mi",
            "themeEndColor": "#0764AB",
            "themeStartColor": "#10D6D5",
            "playerImage": "https://i.ibb.co/sbL5qhs/834.webp",
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 11,
            "totalRuns": 297,
            "totalWickets": 0,
            "dateOfBirth": "17 December 1992",
            "iplDebut": 2013
        },
        {
            "playerId": 1636820044256,
            "playerName": "Jasprit Bumrah",
            "playerTeam": "mi",
            "themeEndColor": "#0764AB",
            "themeStartColor": "#10D6D5",
            "playerImage": "https://i.ibb.co/164SZnQ/1124.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 14,
            "totalRuns": 16,
            "totalWickets": 21,
            "dateOfBirth": "06 December 1993",
            "iplDebut": 2013
        },
        {
            "playerId": 1636820178280,
            "playerName": "Kieron Pollard",
            "playerTeam": "mi",
            "themeEndColor": "#0764AB",
            "themeStartColor": "#10D6D5",
            "playerImage": "https://i.ibb.co/dmyyNx1/210.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 14,
            "totalRuns": 245,
            "totalWickets": 5,
            "dateOfBirth": "\t12 May 1987",
            "iplDebut": 2010
        },
        {
            "playerId": 1636820368125,
            "playerName": "Hardik Pandya",
            "playerTeam": "mi",
            "themeEndColor": "#0764AB",
            "themeStartColor": "#10D6D5",
            "playerImage": "https://i.ibb.co/cC2Rfvw/2740.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 12,
            "totalRuns": 127,
            "totalWickets": 0,
            "dateOfBirth": "11 October 1993",
            "iplDebut": 2015
        },
        {
            "playerId": 1636820968371,
            "playerName": "MS Dhoni",
            "playerTeam": "csk",
            "themeEndColor": "#DFA925",
            "themeStartColor": "#F0D513",
            "playerImage": "https://i.ibb.co/c3535M6/1.webp",
            "playerRole": "wicket_keeper",
            "isCaptain": true,
            "nationality": "Indian",
            "totalMatches": 16,
            "totalRuns": 114,
            "totalWickets": 0,
            "dateOfBirth": "7 July 1981 ",
            "iplDebut": 2007
        },
        {
            "playerId": 1636821134901,
            "playerName": "Ravindra Jadeja",
            "playerTeam": "csk",
            "themeEndColor": "#DFA925",
            "themeStartColor": "#F0D513",
            "playerImage": "https://i.ibb.co/fYkvBV2/9.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 16,
            "totalRuns": 227,
            "totalWickets": 13,
            "dateOfBirth": "06 December 1988 ",
            "iplDebut": 2007
        },
        {
            "playerId": 1636821340668,
            "playerName": " Faf du Plessis",
            "playerTeam": "csk",
            "themeEndColor": "#DFA925",
            "themeStartColor": "#F0D513",
            "playerImage": "https://i.ibb.co/SnM6Mkc/24.webp",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 16,
            "totalRuns": 633,
            "totalWickets": 0,
            "dateOfBirth": "13 July 1984",
            "iplDebut": 2011
        },
        {
            "playerId": 1636821410451,
            "playerName": "Dwayne Bravo",
            "playerTeam": "csk",
            "themeEndColor": "#DFA925",
            "themeStartColor": "#F0D513",
            "playerImage": "https://i.ibb.co/rdsmY4h/25.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "West Indian",
            "totalMatches": 11,
            "totalRuns": 47,
            "totalWickets": 14,
            "dateOfBirth": "07 October 1983",
            "iplDebut": 2008
        },
        {
            "playerId": 1636821489370,
            "playerName": "Ruturaj Gaikwad",
            "playerTeam": "csk",
            "themeEndColor": "#DFA925",
            "themeStartColor": "#F0D513",
            "playerImage": "https://i.ibb.co/GnqWNt1/5443.webp",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 16,
            "totalRuns": 635,
            "totalWickets": 0,
            "dateOfBirth": "31 January 1997",
            "iplDebut": 2018
        },
        {
            "playerId": 1636821799178,
            "playerName": "Virat Kohli",
            "playerTeam": "rcb",
            "themeEndColor": "#B98208",
            "themeStartColor": "#E5BF65",
            "playerImage": "https://i.ibb.co/brH9rbT/164.webp",
            "playerRole": "batsman",
            "isCaptain": true,
            "nationality": "Indian",
            "totalMatches": 15,
            "totalRuns": 405,
            "totalWickets": 0,
            "dateOfBirth": "05 November 1988",
            "iplDebut": 2008
        },
        {
            "playerId": 1636821890716,
            "playerName": "AB de villiers",
            "playerTeam": "rcb",
            "themeEndColor": "#B98208",
            "themeStartColor": "#E5BF65",
            "playerImage": "https://i.ibb.co/9yfGMQ1/233.png",
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 15,
            "totalRuns": 313,
            "totalWickets": 0,
            "dateOfBirth": "17 February 1984",
            "iplDebut": 2008
        },
        {
            "playerId": 1636821976898,
            "playerName": "Glenn Maxwell",
            "playerTeam": "rcb",
            "themeEndColor": "#B98208",
            "themeStartColor": "#E5BF65",
            "playerImage": "https://i.ibb.co/Wvdxd9z/282.webp",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "Australian",
            "totalMatches": 15,
            "totalRuns": 513,
            "totalWickets": 3,
            "dateOfBirth": "14 October 1988",
            "iplDebut": 2012
        },
        {
            "playerId": 1636822042224,
            "playerName": "Yuzvendra Chahal",
            "playerTeam": "rcb",
            "themeEndColor": "#B98208",
            "themeStartColor": "#E5BF65",
            "playerImage": "https://i.ibb.co/WcbmxjW/111.webp",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 15,
            "totalRuns": 10,
            "totalWickets": 18,
            "dateOfBirth": "23 July 1990",
            "iplDebut": 2013
        },
        {
            "playerId": 1636822109742,
            "playerName": "Devdutt Padikkal",
            "playerTeam": "rcb",
            "themeEndColor": "#B98208",
            "themeStartColor": "#E5BF65",
            "playerImage": "https://i.ibb.co/C5WQQbf/5430.webp",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 14,
            "totalRuns": 411,
            "totalWickets": 0,
            "dateOfBirth": "\t07 July 2000",
            "iplDebut": 2018
        },
        {
            "playerId": 1636823146357,
            "playerName": "Rishabh Pant",
            "playerTeam": "dc",
            "themeEndColor": "#B9241A",
            "themeStartColor": "#DCB52F",
            "playerImage": "https://i.ibb.co/0fqxhM6/2972.webp",
            "playerRole": "wicket_keeper",
            "isCaptain": true,
            "nationality": "Indian",
            "totalMatches": 16,
            "totalRuns": 419,
            "totalWickets": 0,
            "dateOfBirth": "04 october 1997",
            "iplDebut": 2016
        },
        {
            "playerId": 1636823320530,
            "playerName": "Anrich Nortje",
            "playerTeam": "dc",
            "themeEndColor": "#B9241A",
            "themeStartColor": "#DCB52F",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/5433.png",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 8,
            "totalRuns": 0,
            "totalWickets": 12,
            "dateOfBirth": "16 November 1993",
            "iplDebut": 2020
        },
        {
            "playerId": 1636823409466,
            "playerName": "Kagiso Rabada",
            "playerTeam": "dc",
            "themeEndColor": "#B9241A",
            "themeStartColor": "#DCB52F",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/1664.png",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 15,
            "totalRuns": 13,
            "totalWickets": 15,
            "dateOfBirth": "25 May 1995",
            "iplDebut": 2017
        },
        {
            "playerId": 1636823515954,
            "playerName": "Shreyas Iyer",
            "playerTeam": "dc",
            "themeEndColor": "#B9241A",
            "themeStartColor": "#DCB52F",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/1563.png",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 8,
            "totalRuns": 175,
            "totalWickets": 0,
            "dateOfBirth": "6 December 1994",
            "iplDebut": 2015
        },
        {
            "playerId": 1636823586473,
            "playerName": "Shikhar Dhawan",
            "playerTeam": "dc",
            "themeEndColor": "#B9241A",
            "themeStartColor": "#DCB52F",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/41.png",
            "playerRole": "batsman",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 16,
            "totalRuns": 587,
            "totalWickets": 0,
            "dateOfBirth": "5 December 1985",
            "iplDebut": 2008
        },
        {
            "playerId": 1636823848072,
            "playerName": "Sanju Samson",
            "playerTeam": "rr",
            "themeEndColor": "#163B97",
            "themeStartColor": "#315DC9",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/258.png",
            "playerRole": "wicket_keeper",
            "isCaptain": true,
            "nationality": "Indian",
            "totalMatches": 14,
            "totalRuns": 484,
            "totalWickets": 0,
            "dateOfBirth": "11 November 1994",
            "iplDebut": 2013
        },
        {
            "playerId": 1636824142971,
            "playerName": "Chris Morris",
            "playerTeam": "rr",
            "themeEndColor": "#163B97",
            "themeStartColor": "#315DC9",
            "playerImage": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/playerheadshot/ipl/284/836.png",
            "playerRole": "all-rounder",
            "isCaptain": false,
            "nationality": "South African",
            "totalMatches": 11,
            "totalRuns": 67,
            "totalWickets": 15,
            "dateOfBirth": "3 April 1987",
            "iplDebut": 2013
        },
        {
            "playerId": 1636824671148,
            "playerName": "Mustafizur Rehman",
            "playerTeam": "rr",
            "themeEndColor": "#163B97",
            "themeStartColor": "#315DC9",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/1594.png",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Bangladeshi",
            "totalMatches": 14,
            "totalRuns": 8,
            "totalWickets": 14,
            "dateOfBirth": "06 September 1995",
            "iplDebut": 2016
        },
        {
            "playerId": 1636824746154,
            "playerName": "Jos Buttler",
            "playerTeam": "rr",
            "themeEndColor": "#163B97",
            "themeStartColor": "#315DC9",
            "playerImage": `https://assets.iplt20.com/ipl/IPLHeadshot2022/509.png`,
            "playerRole": "wicket_keeper",
            "isCaptain": false,
            "nationality": "English",
            "totalMatches": 7,
            "totalRuns": 254,
            "totalWickets": 0,
            "dateOfBirth": "08 September 1990",
            "iplDebut": 2016
        },
        {
            "playerId": 1636824814682,
            "playerName": "Rahul Tewatia",
            "playerTeam": "rr",
            "themeEndColor": "#163B97",
            "themeStartColor": "#315DC9",
            "playerImage": "https://assets.iplt20.com/ipl/IPLHeadshot2022/1749.png",
            "playerRole": "bowler",
            "isCaptain": false,
            "nationality": "Indian",
            "totalMatches": 14,
            "totalRuns": 155,
            "totalWickets": 8,
            "dateOfBirth": "20 May 1993",
            "iplDebut": 2014
        }
    ]
export default Data;